version: '3.7'
services:

  node:
    image: vuejs-docker-setup:local
    build:
      context: ./docker
      dockerfile: Dockerfile
    user: "node"
    working_dir: /home/node/app
    env_file:
      - "./local.env"
    ports:
      - "3000:8080"
    volumes:
      - ./app:/home/node/app:rw,cached
    command: "npm run serve"