[global.limits]
json = 5242880

[default]
address = "127.0.0.1"
port = 8000
keep_alive = 0
limits = { forms = 65536 }

# (optional) export environment variable to use: ROCKET_PROFILE = "debug"
[debug]
workers = 2
log_level = "debug"

# export environment variable to use: ROCKET_PROFILE = "release"
[release]
workers = 2
log_level = "critical"
