[global.limits]
json = 5242880

[default]
address = "127.0.0.1"
port = 8000
keep_alive = 0
limits = { forms = 65536 }

[debug]
ROCKET_PROFILE = "debug"
workers = 2
log_level = "debug"

[release]
ROCKET_PROFILE = "release"
workers = 2
log_level = "critical"
